"""
class_utils.py

Joins each validated DICOM case to its ground-truth clinical label and checks
that every case that passed validation has a label before conversion begins.

## Role in the pipeline

By the time this module runs, each case has been validated for DICOM integrity
and geometric correctness. What we still do not know is whether each case has an
aneurysm or not — that is the supervised label the CNN is trained to predict.

The ground-truth labels live in ``dataset/classes.csv``, a file created manually
from clinical records. This module reads that file and attaches the label to each
case record so the NIfTI conversion step can place the output file into the
correct class subdirectory (``0/`` for healthy, ``1/`` for aneurysm).

## classes.csv format

  exam     — canonical case name (e.g. ``BP001``)
  class    — ``0`` (no aneurysm) or ``1`` (aneurysm present)
  location — anatomical location of the aneurysm (blank for class 0 cases)
  Age      — patient age at time of scan

``classes.csv`` is the only file in the repository that encodes clinical ground
truth. It is never generated by code.

## Suffix handling

When two raw DICOM folders map to the same patient (e.g. ``bp1`` and ``bp001``
both become ``BP001``), ``file_utils`` assigns them disambiguating suffixes:
``BP001A`` and ``BP001B``. Both folders belong to the same patient and share
the same label in the CSV (which stores only ``BP001``). The join strips the
suffix before looking up the label so both records receive the correct class.

Public API (called by data_cleaner.py):
  - join_class_data(validated_data, classes_csv_path)  : attach labels to records
  - check_missing_class(data)                          : flag unlabelled OK cases
"""

import logging
import csv
import re

logger = logging.getLogger("dicom_ingestion")


# ----------------------------------------------------
# 1. Classification Join
# ----------------------------------------------------


def join_class_data(validated_data: list[dict], classes_csv_path: str) -> list[dict]:
    """
    Attaches ground-truth labels from ``classes.csv`` to each validated case record.

    **Reading the CSV:**
    The CSV is loaded into a dictionary keyed by uppercase exam name so lookups
    are O(1) regardless of dataset size. The ``exam`` column values are
    uppercased on load to make the match case-insensitive (the CSV may use
    ``bp001`` while the pipeline produces ``BP001``).

    **Suffix stripping:**
    A case whose ``fixed_name`` is ``BP001A`` or ``BP001B`` (a disambiguated
    duplicate from ``file_utils``) must still match the ``BP001`` entry in the
    CSV, since both folders belong to the same patient. The regex ``(BP\\d+)``
    extracts just the base name and ignores any trailing letters.

    **Fields added to each record:**
      - ``class``       : ``'0'`` (healthy) or ``'1'`` (aneurysm)
      - ``location``    : anatomical location string, or blank for healthy cases
      - ``patient_age`` : patient age at time of scan, read from the ``Age`` column

    If a case name is not found in the CSV (e.g. a case that was collected but
    not yet labelled), no fields are added. ``check_missing_class`` will
    subsequently detect and flag any ``OK`` case that has no label.

    If ``classes.csv`` does not exist at the given path, the function logs a
    warning and returns the data list unchanged rather than crashing the pipeline.

    Args:
        validated_data: List of case record dicts as returned by ``dicom_utils.validate_dcms``.
        classes_csv_path: Absolute path to ``dataset/classes.csv``.

    Returns:
        The same list with ``'class'``, ``'location'``, and ``'patient_age'``
        merged into each record that has a matching CSV entry (in-place).
    """
    logger.info(f"\nJoining data from '{classes_csv_path}'...")
    class_map = {}
    try:
        with open(classes_csv_path, 'r', newline='', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                # Normalise to uppercase so 'bp001' and 'BP001' both match.
                exam_name = row.get('exam', '').strip().upper()
                if exam_name:
                    class_map[exam_name] = {
                        'class': row.get('class'),
                        'location': row.get('location'),
                        'patient_age': row.get('Age')
                    }
    except FileNotFoundError:
        logger.warning(f"  - Warning: Classes file not found at '{classes_csv_path}'. Skipping join.")
        return validated_data

    for item in validated_data:
        # Strip any alphabetic suffix (e.g. 'BP001A' → 'BP001') before lookup,
        # since duplicate folders from the same patient share one CSV entry.
        match = re.match(r"(BP\d+)", item.get('fixed_name', ''))
        if match:
            base_name = match.group(1)
            class_info = class_map.get(base_name, {})
            item.update(class_info)
    return validated_data


# ----------------------------------------------------
# 2. Missing Class Check
# ----------------------------------------------------


def check_missing_class(data: list[dict]) -> list[dict]:
    """
    Flags any validated case that passed DICOM checks but has no clinical label.

    A case can reach this point with ``validation_status == 'OK'`` but no
    ``'class'`` key if its name was absent from ``classes.csv`` — for example,
    a recently collected scan that has not yet been reviewed and labelled by a
    clinician.

    Such cases cannot be used for supervised training (the CNN has no target to
    learn from) and must not be passed to the NIfTI conversion step. Their status
    is updated to ``'MISSING_CLASS'`` so they are excluded downstream and flagged
    clearly in the audit log.

    Cases that already have a non-OK status (e.g. ``VARIABLE_SPACING``,
    ``MIXED_SERIES_ERROR``) are intentionally left untouched — they are already
    excluded from conversion for a different reason, and overwriting their status
    would lose that diagnostic information in the audit log.

    Args:
        data: List of case record dicts after ``join_class_data`` has run.

    Returns:
        The same list with ``validation_status`` updated to ``'MISSING_CLASS'``
        for any OK case that has no label (in-place).
    """
    logger.info("\nChecking for missing classifications in 'OK' exams...")
    missing_class_count = 0
    for item in data:
        if item.get('validation_status') == 'OK' and not item.get('class'):
            item['validation_status'] = 'MISSING_CLASS'
            missing_class_count += 1

    logger.info(f"  - Flagged {missing_class_count} 'OK' exams with status 'MISSING_CLASS'.")
    return data
